name: main branch action

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t unbound-minfwd:latest .
      - name: DH login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Push to DH
        run: |
          docker tag unbound-minfwd:latest ${{ secrets.DOCKERHUB_USER }}/unbound-minfwd:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/unbound-minfwd:latest
